### ISSUE TITLE
Feature request - light mode for code editor

### ISSUE THREAD

**Issue by cyberwombat** [yozorajs/yozora-react#1]
Thanks for improving the editor!  I see that you have dark mode hard coded - would it be possible to have a light/dark toggle to match the website light/dark mode?

**Comment by guanghechen** [comment]
Hi @cyberwombat, thank you for your use and feedback. 

Now I have added a `dark` option in the [@yozora/react-code-editor][], [@yozora/react-code-highlighter][] and [@yozora/react-code-live][] to support toggling the default theme (its default value is `true`). By the way, you can specify your own prism theme object through the `theme` option.

Hope it’s not too late. :)

[@yozora/react-code-editor]: https://github.com/guanghechen/yozora-react/tree/master/packages/code-editor#readme
[@yozora/react-code-highlighter]: https://github.com/guanghechen/yozora-react/tree/master/packages/code-highlighter#readme
[@yozora/react-code-live]: https://github.com/guanghechen/yozora-react/tree/master/packages/code-live#readme

**Comment by cyberwombat** [comment]
Awe you're the best!  Thank you.
